"""Add pipeline_status and pipeline_error to resumes table.

Revision ID: add_pipeline_status_fields
Revises: add_user_settings_table
Create Date: 2026-04-09

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_pipeline_status_fields'
down_revision = 'add_user_settings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('pipeline_status', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('pipeline_error', sa.Text(), nullable=True))
    op.alter_column('resumes', 'pipeline_status',
                    existing_type=sa.String(),
                    server_default='pending')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'pipeline_status',
                    existing_type=sa.String(),
                    server_default=None,
                    existing_server_default='pending')
    op.drop_column('resumes', 'pipeline_error')
    op.drop_column('resumes', 'pipeline_status')
    # ### end Alembic commands ###
